import Foundation
import Testing
@testable import ClipVaultCore

// 测试用的假 token：格式命中检测规则，但显然不是真实凭证。
private let fakeGitHubToken = "ghp_" + String(repeating: "Fake0", count: 8)
private let fakeJWT = "eyJ" + String(repeating: "a", count: 20) + "." + "eyJ" + String(repeating: "b", count: 20) + "." + String(repeating: "c", count: 10)

@Suite("CapturePolicy")
struct CapturePolicyTests {
    let settings = CVSettings.default

    @Test("普通文本被接受")
    func plainTextAccepted() {
        let d = CapturePolicy.evaluate(text: "hello world", imageByteCount: nil,
                                       flags: .init(), sourceBundleID: "com.apple.dt.Xcode",
                                       settings: settings)
        #expect(d == .acceptText(sensitive: false))
    }

    @Test("空白文本被拒绝")
    func emptyRejected() {
        let d = CapturePolicy.evaluate(text: "   \n ", imageByteCount: nil,
                                       flags: .init(), sourceBundleID: nil, settings: settings)
        #expect(d == .reject(.empty))
    }

    @Test("Concealed 标记被跳过")
    func concealedRejected() {
        let d = CapturePolicy.evaluate(text: "password-like", imageByteCount: nil,
                                       flags: .init(concealed: true), sourceBundleID: nil,
                                       settings: settings)
        #expect(d == .reject(.concealed))
    }

    @Test("关闭 skipConcealed 后 Concealed 可入库")
    func concealedAcceptedWhenDisabled() {
        var s = settings
        s.skipConcealed = false
        let d = CapturePolicy.evaluate(text: "some text", imageByteCount: nil,
                                       flags: .init(concealed: true), sourceBundleID: nil, settings: s)
        #expect(d == .acceptText(sensitive: false))
    }

    @Test("Transient / AutoGenerated 被跳过")
    func transientRejected() {
        let d1 = CapturePolicy.evaluate(text: "x", imageByteCount: nil,
                                        flags: .init(transient: true), sourceBundleID: nil,
                                        settings: settings)
        let d2 = CapturePolicy.evaluate(text: "x", imageByteCount: nil,
                                        flags: .init(autoGenerated: true), sourceBundleID: nil,
                                        settings: settings)
        #expect(d1 == .reject(.transient))
        #expect(d2 == .reject(.transient))
    }

    @Test("排除应用（大小写不敏感）")
    func excludedApp() {
        var s = settings
        s.excludedBundleIDs = ["com.example.SecretApp"]
        let d = CapturePolicy.evaluate(text: "anything", imageByteCount: nil,
                                       flags: .init(), sourceBundleID: "com.example.secretapp",
                                       settings: s)
        #expect(d == .reject(.excludedApp))
    }

    @Test("超大文本被拒绝")
    func textTooLarge() {
        var s = settings
        s.maxTextBytes = 10
        let d = CapturePolicy.evaluate(text: String(repeating: "a", count: 11), imageByteCount: nil,
                                       flags: .init(), sourceBundleID: nil, settings: s)
        #expect(d == .reject(.textTooLarge))
    }

    @Test("图片大小限制")
    func imageSizeLimit() {
        var s = settings
        s.maxImageBytes = 1000
        let ok = CapturePolicy.evaluate(text: nil, imageByteCount: 999,
                                        flags: .init(), sourceBundleID: nil, settings: s)
        let tooBig = CapturePolicy.evaluate(text: nil, imageByteCount: 1001,
                                            flags: .init(), sourceBundleID: nil, settings: s)
        #expect(ok == .acceptImage)
        #expect(tooBig == .reject(.imageTooLarge))
    }

    @Test("关闭图片保存")
    func imagesDisabled() {
        var s = settings
        s.keepImages = false
        let d = CapturePolicy.evaluate(text: nil, imageByteCount: 10,
                                       flags: .init(), sourceBundleID: nil, settings: s)
        #expect(d == .reject(.imagesDisabled))
    }

    @Test("密钥策略：mask → 记录但标记敏感")
    func secretMask() {
        let d = CapturePolicy.evaluate(text: "token: \(fakeGitHubToken)", imageByteCount: nil,
                                       flags: .init(), sourceBundleID: nil, settings: settings)
        #expect(d == .acceptText(sensitive: true))
    }

    @Test("密钥策略：ignore → 不记录")
    func secretIgnore() {
        var s = settings
        s.secretPolicy = .ignore
        let d = CapturePolicy.evaluate(text: fakeGitHubToken, imageByteCount: nil,
                                       flags: .init(), sourceBundleID: nil, settings: s)
        #expect(d == .reject(.secretIgnored))
    }

    @Test("密钥策略：off → 当普通文本")
    func secretOff() {
        var s = settings
        s.secretPolicy = .off
        let d = CapturePolicy.evaluate(text: fakeGitHubToken, imageByteCount: nil,
                                       flags: .init(), sourceBundleID: nil, settings: s)
        #expect(d == .acceptText(sensitive: false))
    }
}

@Suite("SecretDetector")
struct SecretDetectorTests {
    @Test("命中常见凭证格式")
    func detectsCommonFormats() {
        #expect(SecretDetector.looksLikeSecret(fakeGitHubToken))
        #expect(SecretDetector.looksLikeSecret(fakeJWT))
        #expect(SecretDetector.looksLikeSecret("AKIA" + String(repeating: "A", count: 16)))
        #expect(SecretDetector.looksLikeSecret("xoxb-1234567890-abcdefghij"))
        #expect(SecretDetector.looksLikeSecret("-----BEGIN RSA PRIVATE KEY-----"))
        #expect(SecretDetector.looksLikeSecret("Authorization: Bearer abcdefghijklmnopqrstuvwxyz123456"))
        #expect(SecretDetector.looksLikeSecret("api_key = supersecretvalue123"))
        #expect(SecretDetector.looksLikeSecret("password: hunter2hunter2"))
    }

    @Test("普通文本不误报")
    func negatives() {
        #expect(!SecretDetector.looksLikeSecret("明天下午三点开会"))
        #expect(!SecretDetector.looksLikeSecret("https://github.com/apple/swift"))
        #expect(!SecretDetector.looksLikeSecret("The quick brown fox jumps over the lazy dog"))
        #expect(!SecretDetector.looksLikeSecret("SELECT id FROM billing_invoices LIMIT 10"))
        #expect(!SecretDetector.looksLikeSecret("password reset 流程明天上线"))
    }

    @Test("超长文本不会卡住")
    func longTextPerformance() {
        let big = String(repeating: "some ordinary log line without anything special\n", count: 100_000)
        let start = Date()
        _ = SecretDetector.looksLikeSecret(big)
        #expect(Date().timeIntervalSince(start) < 1.0)
    }
}
