import Foundation

/// 剪贴板事件上的语义标记（nspasteboard.org 约定，密码管理器普遍遵守）。
public struct PasteboardFlags: Equatable {
    public var concealed: Bool
    public var transient: Bool
    public var autoGenerated: Bool

    public init(concealed: Bool = false, transient: Bool = false, autoGenerated: Bool = false) {
        self.concealed = concealed
        self.transient = transient
        self.autoGenerated = autoGenerated
    }
}

public enum RejectReason: String, Equatable {
    case empty
    case concealed
    case transient
    case excludedApp
    case textTooLarge
    case imageTooLarge
    case imagesDisabled
    case secretIgnored
}

public enum CaptureDecision: Equatable {
    case acceptText(sensitive: Bool)
    case acceptImage
    case reject(RejectReason)
}

/// 纯函数：决定一次剪贴板变更要不要入库。所有安全规则集中在这里，便于测试。
public enum CapturePolicy {
    public static func evaluate(
        text: String?,
        imageByteCount: Int?,
        flags: PasteboardFlags,
        sourceBundleID: String?,
        settings: CVSettings
    ) -> CaptureDecision {
        if settings.skipConcealed && flags.concealed { return .reject(.concealed) }
        if settings.skipTransient && (flags.transient || flags.autoGenerated) { return .reject(.transient) }
        if let bid = sourceBundleID,
           settings.excludedBundleIDs.contains(where: { $0.caseInsensitiveCompare(bid) == .orderedSame }) {
            return .reject(.excludedApp)
        }

        if let imageByteCount {
            guard settings.keepImages else { return .reject(.imagesDisabled) }
            guard imageByteCount <= settings.maxImageBytes else { return .reject(.imageTooLarge) }
            return .acceptImage
        }

        guard let text, !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .reject(.empty)
        }
        guard text.utf8.count <= settings.maxTextBytes else { return .reject(.textTooLarge) }

        if settings.secretPolicy != .off && SecretDetector.looksLikeSecret(text) {
            if settings.secretPolicy == .ignore { return .reject(.secretIgnored) }
            return .acceptText(sensitive: true)
        }
        return .acceptText(sensitive: false)
    }
}
