import Foundation

/// 命中密钥/Token 检测后的处理策略。
public enum SecretPolicy: String, Codable, CaseIterable {
    /// 直接不记录
    case ignore
    /// 记录，但在列表中遮罩显示（默认）
    case mask
    /// 不检测
    case off
}

public struct CVSettings: Codable, Equatable {
    /// 保留时长（小时），0 = 永久
    public var retentionHours: Int = 72
    public var maxItems: Int = 500
    public var keepImages: Bool = true
    public var maxImageBytes: Int = 10 * 1024 * 1024
    public var maxTextBytes: Int = 1024 * 1024
    /// 跳过密码管理器标记的 org.nspasteboard.ConcealedType 内容
    public var skipConcealed: Bool = true
    /// 跳过 Transient / AutoGenerated 标记内容
    public var skipTransient: Bool = true
    public var secretPolicy: SecretPolicy = .mask
    public var excludedBundleIDs: [String] = CVSettings.defaultExcludedApps
    /// true = AES-GCM 加密落盘；false = 仅内存，退出即清空
    public var persistToDisk: Bool = true
    /// 选中条目后自动向前台应用发送 ⌘V（需要辅助功能权限）
    public var autoPaste: Bool = false
    public var launchAtLogin: Bool = false
    /// 全局热键预设标识（App 层解释）
    public var hotkey: String = "ctrlShiftV"

    public static let defaultExcludedApps: [String] = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "in.sinew.Enpass-Desktop",
        "com.dashlane.dashlanephonefinal",
        "me.proton.pass.electron",
    ]

    public init() {}

    public static let `default` = CVSettings()

    private enum CodingKeys: String, CodingKey {
        case retentionHours, maxItems, keepImages, maxImageBytes, maxTextBytes
        case skipConcealed, skipTransient, secretPolicy, excludedBundleIDs
        case persistToDisk, autoPaste, launchAtLogin, hotkey
    }

    // 手写 decode：缺字段时用默认值，便于后续版本加字段不破坏旧配置。
    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        let d = CVSettings.default
        retentionHours = try c.decodeIfPresent(Int.self, forKey: .retentionHours) ?? d.retentionHours
        maxItems = try c.decodeIfPresent(Int.self, forKey: .maxItems) ?? d.maxItems
        keepImages = try c.decodeIfPresent(Bool.self, forKey: .keepImages) ?? d.keepImages
        maxImageBytes = try c.decodeIfPresent(Int.self, forKey: .maxImageBytes) ?? d.maxImageBytes
        maxTextBytes = try c.decodeIfPresent(Int.self, forKey: .maxTextBytes) ?? d.maxTextBytes
        skipConcealed = try c.decodeIfPresent(Bool.self, forKey: .skipConcealed) ?? d.skipConcealed
        skipTransient = try c.decodeIfPresent(Bool.self, forKey: .skipTransient) ?? d.skipTransient
        secretPolicy = try c.decodeIfPresent(SecretPolicy.self, forKey: .secretPolicy) ?? d.secretPolicy
        excludedBundleIDs = try c.decodeIfPresent([String].self, forKey: .excludedBundleIDs) ?? d.excludedBundleIDs
        persistToDisk = try c.decodeIfPresent(Bool.self, forKey: .persistToDisk) ?? d.persistToDisk
        autoPaste = try c.decodeIfPresent(Bool.self, forKey: .autoPaste) ?? d.autoPaste
        launchAtLogin = try c.decodeIfPresent(Bool.self, forKey: .launchAtLogin) ?? d.launchAtLogin
        hotkey = try c.decodeIfPresent(String.self, forKey: .hotkey) ?? d.hotkey
    }
}
