import AppKit
import ClipVaultCore

/// 一次剪贴板变更的原始快照。图片转码等重活交给 HistoryController 在后台线程做。
struct CaptureCandidate {
    var text: String?
    var rawImageData: Data?
    var rawImageIsPNG: Bool = false
    var flags = PasteboardFlags()
    var sourceBundleID: String?
    var sourceAppName: String?
}

/// NSPasteboard 没有变更通知，只能轮询 changeCount（Maccy/Alfred 同款做法）。
/// 每次 tick 只比较一个整数，代价可忽略。
final class PasteboardWatcher {
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private let pasteboard = NSPasteboard.general
    private var changeCount: Int
    private var timer: Timer?

    var onCandidate: ((CaptureCandidate) -> Void)?

    init() {
        changeCount = pasteboard.changeCount
    }

    func start(intervalMS: Int) {
        stop()
        let t = Timer(timeInterval: Double(intervalMS) / 1000.0, repeats: true) { [weak self] _ in
            self?.tick()
        }
        t.tolerance = Double(intervalMS) / 1000.0 * 0.3
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount

        guard let types = pasteboard.types, !types.isEmpty else { return }

        var candidate = CaptureCandidate()
        candidate.flags = PasteboardFlags(
            concealed: types.contains(Self.concealedType),
            transient: types.contains(Self.transientType),
            autoGenerated: types.contains(Self.autoGeneratedType)
        )
        let front = NSWorkspace.shared.frontmostApplication
        candidate.sourceBundleID = front?.bundleIdentifier
        candidate.sourceAppName = front?.localizedName

        // 图片优先：浏览器复制图片时往往同时带 URL 文本
        if types.contains(.png), let data = pasteboard.data(forType: .png) {
            candidate.rawImageData = data
            candidate.rawImageIsPNG = true
        } else if types.contains(.tiff), let data = pasteboard.data(forType: .tiff) {
            candidate.rawImageData = data
            candidate.rawImageIsPNG = false
        } else if types.contains(.fileURL),
                  let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                                    options: [.urlReadingFileURLsOnly: true]) as? [URL],
                  !urls.isEmpty {
            // 复制文件时记录路径列表（v1 不复制文件内容本身）
            candidate.text = urls.map(\.path).joined(separator: "\n")
        } else if let s = pasteboard.string(forType: .string) {
            candidate.text = s
        }

        guard candidate.rawImageData != nil || candidate.text != nil else { return }
        onCandidate?(candidate)
    }
}
